In [59]:
import pandas as pd
import numpy as np
import scipy.stats
pd.__version__

'0.22.0'

In [92]:
1//2

0

## *str*

The string

In [88]:
arr = np.array([1,2,3] + [4,5,6])
np.percentile(arr, [50, 75])  # np.median(arr)

array([3.5 , 4.75])

In [65]:
arr2 = np.array([1,2,3,3,3,4,4,4,4,4,4,5,6])
stats.mode(arr2)

ModeResult(mode=array([4]), count=array([6]))

In [36]:
a1 = np.random.randint(5,8, (3,4))
a1.reshape(2, -1)

array([[5, 5, 7, 5, 5, 6],
       [5, 6, 6, 7, 7, 7]])

In [49]:
a = np.arange(9).reshape(3,3)
b = np.random.randint(9,18, (3,3))
c = np.vstack((a,b))
c

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [12, 14, 15],
       [12, 10, 11],
       [13, 13,  9]])

In [67]:
np.concatenate((a,b),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [12, 14, 15],
       [12, 10, 11],
       [13, 13,  9]])

In [52]:
c.mean(axis=1)

array([ 1.        ,  4.        ,  7.        , 13.66666667, 11.        ,
       11.66666667])

In [79]:
a / 2

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [73]:
temp = [1,2,3,4,5]
temp2 = [x for x in temp if x > 3]
temp2

[4, 5]

In [76]:
tup = (1,2)
tup[0] == 3  # tup[0] = 3

False

In [85]:
1 * 1.0

1.0

In [93]:
2%8

2

In [95]:
tup = (1, "tup")
tup

(1, 'tup')

In [102]:
s = "string"
s[-1]

'g'

In [106]:
l = [1,2,3]
l[0] = 4
l

[4, 2, 3]

In [107]:
l = [1,2,3,2,3,2,1,2,3,4,5,4,5,4,3,4,5,6,7,6,7,5]
l = set(l)
list(l)

[1, 2, 3, 4, 5, 6, 7]

In [109]:
s = 'string'
ss = "string"
s == ss

True

In [122]:
d = {'key1': "Tim Mays", 'key2': ['soccer', 25, '2018']}
#list(d.values())
d['key2'][-1]

'2018'

In [123]:
d2 = {'key1': "Tim Mays", 'key2': {'team':'soccer', 'age': 25, 'year':'2018'}}
d2['key2']['year']

'2018'

In [142]:
s = set([1,2,3,1,2,3])
1 in s

True

In [137]:
for i in range(5):
    print(i)
list(range(5, 10))

0
1
2
3
4


[5, 6, 7, 8, 9]

In [139]:
L = [-1,-2,-3,-4,-5]
LL = [num**2 for num in L]
LL

[1, 4, 9, 16, 25]

In [141]:
L = [-1,-2,-3,-4,-5]
LL = [abs(num) for num in L]
LL

[1, 2, 3, 4, 5]

In [160]:

df = pd.read_csv("iris.csv", names = ["sepal_l", "sepal_w", "petal_l", "petal_w", "class"])
df.head()

sepal_l  sepal_w  petal_l  petal_w        class
0      5.1      3.5      1.4      0.2  Iris-setosa
1      4.9      3.0      1.4      0.2  Iris-setosa
2      4.7      3.2      1.3      0.2  Iris-setosa
3      4.6      3.1      1.5      0.2  Iris-setosa
4      5.0      3.6      1.4      0.2  Iris-setosa

In [165]:
def f(indiv):
    if indiv[0] == 'player':
        if indiv[1] < 19 or indiv[1] > 25:
            return False
        else:
            return True
    else:
        if indiv[1] > 25:
            return True
        else:
            return False
    

In [169]:
f(('coach', 23))

False